In [59]:
import numpy as np

# Numpy 입출력
Numpy는 배열 객체를 바이너리 파일 혹은 텍스트파일에 저장하고 로딩할 수 있다.  

| 함수명       | 기능                                | 파일포맷 |
|--------------|-------------------------------------|----------|
| np.save()    | Numpy배열 객체 1개를 파일에 저장    | 바이너리 |
| np.savez()   | Numpy배열 여러개를 파일에 저장      | 바이너리 |
| np.load()    | Numpy배열 저장 파일로부터 객체 로딩 | 바이너리 |
| np.loadtxt() | 텍스트파일로부터 배열 로딩          | 텍스트   |
| np.savetxt() | 텍스트파일에 Numpy배열 객체 저장    | 텍스트   |

In [60]:
a = np.random.randint(0,10,(2,3))
b = np.random.randint(0,10, (2,3))
pprint(a)
pprint(b)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[4 2 5]
 [2 2 2]]
type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 0 8]
 [4 0 9]]


**배열 객체 저장**
np.save, np.savez 함수를 이용하여 배열 객체를 파일로 저장
* np.save: 1개 배열 저장, 확장자:npy
* np.savez: 여러개 배열 저장, 확장자:npz
* 바이너리파일로 저장

In [61]:
np.save("./my_array1", a)

In [62]:
np.savez("./my_array2",a,b)

* npy와 npz파일은 np.load() 함수로 읽어온다

In [63]:
np.load("./my_array1.npy")

array([[4, 2, 5],
       [2, 2, 2]])

In [65]:
npzfiles = np.load("./my_array2.npz")
npzfiles.files

['arr_0', 'arr_1']

In [66]:
npzfiles['arr_0']

array([[4, 2, 5],
       [2, 2, 2]])

In [67]:
npzfiles['arr_1']

array([[1, 0, 8],
       [4, 0, 9]])

**텍스트파일 로딩**
텍스트파일을 np.loadtxt()로 로드할 수 있다.
* np.loadtxt(fname, dtype=<class float>, comments='#', delimiter=None, convertesr=None, skiprows=0, usecols=None, unpack=False, ndmin=0)
    * fname: 파일명
    * dtype: 데이터 타입
    * comments: comment 시작 부호
    * delimiter: 구분자
    * skiprows: 제외 라인 수(header 제거)