# 4. 데이터 타입
dtype의 값
* np.int64 
* np.float32 
* np.complex : 복소수(128float)
* np.bool (T / F)
* np.object : 파이썬 객체
* np.string_
* np.uniconde_

# 5. 배열 상태 검사
배열의 현재 상태를 검사하는 방법들

| 배열속성 검사 항목 | 배열속성 확인 방법      | 예시               | 결과                   |
|--------------------|-------------------------|--------------------|------------------------|
| 배열 shape         | np.ndarray.shape 속성   | arr.shape          | (5,2,3)                |
| 배열 길이          | 일차원 배열의 길이 확인 | len(arr)           | 5                      |
| 배열 차원          | np.ndarray.ndim 속성    | arr.ndim           | 3                      |
| 배열 요소 수       | np.ndarray.size         | arr.size           | 30                     |
| 배열 타입          | np.ndarray.dtype        | arr.dtype          | dtype("float64")       |
| 배열 타입 명       | np.ndarray.dtype.name   | arr.dtype.name     | float64                |
| 배열 타입 변환     | np.ndarray.astype       | arr.astype(np.int) | 데이터타입 정수로 변환 |

In [2]:
import numpy as np
#데모 배열 객체 생성
arr = np.random.random((5,2,3))


In [3]:
type(arr)

numpy.ndarray

In [4]:
# 배열의 shape 확인
arr.shape

(5, 2, 3)

In [5]:
# 배열의 길이
len(arr)

5

In [6]:
# 배열의 차원 수 
arr.ndim

3

In [7]:
# 배열의 요소 수: shape(k, m, n) ==> k*m*n
arr.size

30

In [8]:
# 배열 타입 확인
arr.dtype

dtype('float64')

In [9]:
# 배열 타입명 
arr.dtype.name

'float64'

In [10]:
# 배열 요소를 int로 변환
# 요소의 실제 값이 변환되는 것이 아님
# View의 출력 타입과 연산을 변환하는 것
arr.astype(np.int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [11]:
# np.float으로 타입을 다시 변환하면 np.int 변환 이전 값으로 모든 원소 값이 복원됨
arr.astype(np.float)

array([[[0.02557523, 0.45558396, 0.16633608],
        [0.33645378, 0.3307826 , 0.57263535]],

       [[0.98249684, 0.93234629, 0.36632965],
        [0.39016747, 0.83974036, 0.20111327]],

       [[0.50314179, 0.63333571, 0.52770013],
        [0.52555133, 0.10754029, 0.71007298]],

       [[0.15410234, 0.78540415, 0.30414841],
        [0.98104802, 0.59605432, 0.82670221]],

       [[0.80076743, 0.50797962, 0.59382932],
        [0.3689813 , 0.72291585, 0.34677129]]])

# 6. 도움말
npinfo() 함수를 통해 도움말 볼 수 있어

In [12]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
