In [1]:
import numpy as np

def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

# Numpy 객체정보를 출력하는 용도

# 7. 배열 연산
### 7.1 배열 일반 연산
  
  ### 산술 연산
 

In [3]:
import numpy as np

a = np.arange(1,10).reshape(3,3)
pprint(a)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [6]:
a - b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [8]:
np.subtract(a,b)

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [7]:
a + b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [9]:
np.add(a,b)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [10]:
a / b

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [11]:
np.divide(a,b)

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [12]:
a * b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [13]:
np.multiply(a,b)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [14]:
np.exp(b)

array([[8.10308393e+03, 2.98095799e+03, 1.09663316e+03],
       [4.03428793e+02, 1.48413159e+02, 5.45981500e+01],
       [2.00855369e+01, 7.38905610e+00, 2.71828183e+00]])

In [15]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [16]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [17]:
np.cos(b)

array([[-0.91113026, -0.14550003,  0.75390225],
       [ 0.96017029,  0.28366219, -0.65364362],
       [-0.9899925 , -0.41614684,  0.54030231]])

In [18]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [19]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [20]:
np.dot(a,b) # dot product, 내적

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

### 비교 연산
* 기본 연산자를 활용하여 요소별 비교

In [21]:
a == b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [22]:
a > b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

**배열 비교**
* np.array_equal

In [23]:
np.array_equal(a,b)

False

### 집계  함수
Axis를 기준으로 집계함수 계산한다. Default는 None
* axis=None  
* 전체 행렬을 하나의 배열로 간주하고 집계함수의 범위를 전체 행렬로  
![None](https://taewanmerepo.github.io/2018/01/numpy/axis_none.jpg)  
* axis=0
* 행을 기준으로 각 행의 동일 인덱스의 요소를 그룹으로
* 각 그룹을 집계함수 범위로 정의  
![0](https://taewanmerepo.github.io/2018/01/numpy/axis_0.jpg)  
* axis=1
* 열을 기준으로 각 열의 동일 인덱스의 요소를 그룹으로  
![1](https://taewanmerepo.github.io/2018/01/numpy/axis_1.jpg)  
[Numpy에서 np.sum 함수의 axis 이해](http://taewan.kim/post/numpy_sum_axis/) 참조


In [24]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
a.sum() # np.sum(a)

45

In [26]:
a.sum(axis=0)

array([12, 15, 18])

In [27]:
a.sum(axis=1)

array([ 6, 15, 24])

- np.sum() : 합계
- np.min, max() : 최솟값, 최댓값
- np.cumssum() : 누적합계
- np.mean() : 평균
- np.median() : 중앙값
- np.corrcoef : 상관계수
- np.std : 표준편차

### 7.2 브로드캐스팅
![broadcasting](https://taewanmerepo.github.io/2018/01/numpy/broadcast.png)

In [28]:
a = np.arange(1, 25).reshape(4, 6)
pprint(a)
b = np.arange(25, 49).reshape(4, 6)
pprint(b)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


**Shape 같은 배열의 이항 연산**
- shape가 같은 두 배열을 연산할 때, 위치가 같은 요소 단위로 계산

In [29]:
a + b

array([[26, 28, 30, 32, 34, 36],
       [38, 40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70, 72]])

**Shape 다른 두 배열의 연산**
* 서로 모양이 다른 배열을 계산할 때 브로드캐스팅 발생
* 두 배열을 같은 Shape로 만든 후 연산
  
  **Case1: 배열과 스칼라**  
  배열과 스칼라 사이의 연산 시 스칼라를 배열로

In [30]:
a = np.arange(1, 25).reshape(4, 6)
pprint(a)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [31]:
a + 100

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124]])

**Case2: Shape 다른 두 배열들의 연산**  

In [34]:
a = np.arange(5).reshape((1, 5))
pprint(a)
b = np.arange(5).reshape((5, 1))
pprint(b)

type:<class 'numpy.ndarray'>
shape: (1, 5), dimension: 2, dtype:int64
Array's Data:
 [[0 1 2 3 4]]
type:<class 'numpy.ndarray'>
shape: (5, 1), dimension: 2, dtype:int64
Array's Data:
 [[0]
 [1]
 [2]
 [3]
 [4]]


In [35]:
a + b

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### 7.3 벡터연산

In [54]:
a = np.arange(100000000)

* loop 사용한 처리 속도

In [55]:
result=0

In [62]:
%time

for v in a:
    result += v

CPU times: user 10 µs, sys: 0 ns, total: 10 µs
Wall time: 20 µs


In [63]:
result

9999999900000000

In [64]:
%%time
result = np.sum(a)

CPU times: user 121 ms, sys: 72 ms, total: 193 ms
Wall time: 192 ms
