# 8. 배열 복사
ndarray 객체에 대한 slice, subset, indexing은 새로운 배열 객체를 반환하는 것이 아니라 기존 객체의 뷰이다. 밴환한 배열의 값을 변경하면 원본 배열에 반영된다.  
새로운 배열에 기존의 배열의 변화를 저장하려면 copy함수로 기존의 객체와 다른 객체를 만들어야 한다.  
## [ndarray].copy(), np.copy(arr)

In [3]:
import numpy as np

def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

# Numpy 객체정보를 출력하는 용도

In [4]:
a = np.random.randint(0,9, (3,3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[2 6 5]
 [5 0 7]
 [5 5 6]]


In [5]:
copied_a1 = np.copy(a) #

In [6]:
# 전체 row의 첫 번째 요소 0으로 바꿈
copied_a1[:,0]=0
pprint(copied_a1)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[0 6 5]
 [0 0 7]
 [0 5 6]]


In [7]:
pprint(a) # 복사본 변경이 원본에 영향 주지 않음

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[2 6 5]
 [5 0 7]
 [5 5 6]]


# 9. 배열 정렬
axis를 기준으로 요소를 정렬하는 sort

In [8]:
unsorted_arr = np.random.random((3,3))
pprint(unsorted_arr)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:float64
Array's Data:
 [[0.98903776 0.35198078 0.88115804]
 [0.80932609 0.73441259 0.71573055]
 [0.70632638 0.33397799 0.74395499]]


In [9]:
unsorted_arr1 = unsorted_arr.copy()
unsorted_arr2 = unsorted_arr.copy()
unsorted_arr3 = unsorted_arr.copy()

* arr.sort() axis의 기본값은 -1
* axis=-1은 현재 배열의 마지막 axis를 의미
* 현재 unsorted_arr의 마지막 axis는 1

In [10]:
# sort array
unsorted_arr1.sort()
pprint(unsorted_arr1)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:float64
Array's Data:
 [[0.35198078 0.88115804 0.98903776]
 [0.71573055 0.73441259 0.80932609]
 [0.33397799 0.70632638 0.74395499]]


In [11]:
# sort array, axis=0
unsorted_arr2.sort(axis=0)
pprint(unsorted_arr2)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:float64
Array's Data:
 [[0.70632638 0.33397799 0.71573055]
 [0.80932609 0.35198078 0.74395499]
 [0.98903776 0.73441259 0.88115804]]


In [12]:
# sort array, axis=1
unsorted_arr3.sort(axis=1)
pprint(unsorted_arr3)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:float64
Array's Data:
 [[0.35198078 0.88115804 0.98903776]
 [0.71573055 0.73441259 0.80932609]
 [0.33397799 0.70632638 0.74395499]]


![axis=0](https://taewanmerepo.github.io/2018/01/numpy/sortaxis1.jpg)![axis=1](https://taewanmerepo.github.io/2018/01/numpy/sortaxis2.jpg)  
___
# 10. Subset, Slice, Indexing
## 10.1 요소 선택
파이썬 인덱스와 같이 참조 가능  

In [13]:
a0 = np.arange(24) # 1차원 배열
pprint(a0)
a1 = np.arange(24).reshape((4, 6)) #2차원 배열
pprint(a1)
a2 = np.arange(24).reshape((2, 4, 3)) # 3차원 배열
pprint(a2)

type:<class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype:int64
Array's Data:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
type:<class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype:int64
Array's Data:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [14]:
# 1D array indexing
a0[5]

5

In [15]:
a0[5] = 10000
pprint(a0)

type:<class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype:int64
Array's Data:
 [    0     1     2     3     4 10000     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23]


In [16]:
# 2D array indexing
a1[0,1]

1

In [17]:
a1[0,1] = 10000
pprint(a1)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[    0 10000     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]]


In [18]:
# 3D array indexing
a2[1,0,1]

13

In [19]:
a2[1,0,1] = 10000
pprint(a2)

type:<class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype:int64
Array's Data:
 [[[    0     1     2]
  [    3     4     5]
  [    6     7     8]
  [    9    10    11]]

 [[   12 10000    14]
  [   15    16    17]
  [   18    19    20]
  [   21    22    23]]]


## 10.2 Slicing
[a:b] 의 형태로 나타내며 axis 별로 범위를 지정한다.  
a 이상 b 미만  
a를 생략하면 0을 지정한 것으로 간주한다.  
b를 생력하면 마지막 index를 지정한 것으로 간주한다.  
':'은 전체 범위를 의미한다. 

In [20]:
a1 = np.arange(1, 25).reshape((4, 6)) #2차원 배열
pprint(a1)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [21]:
a1[1:3, 1:5]

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

**슬라이싱 업데이트**

In [22]:
pprint(a1)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [23]:
slide_arr = a1[1:3, 1:5]
pprint(slide_arr)

type:<class 'numpy.ndarray'>
shape: (2, 4), dimension: 2, dtype:int64
Array's Data:
 [[ 8  9 10 11]
 [14 15 16 17]]


In [24]:
slide_arr[:, 1:3]

array([[ 9, 10],
       [15, 16]])

In [25]:
slide_arr[:, 1:3] = 9999
pprint(slide_arr)

type:<class 'numpy.ndarray'>
shape: (2, 4), dimension: 2, dtype:int64
Array's Data:
 [[   8 9999 9999   11]
 [  14 9999 9999   17]]


In [27]:
pprint(a1) # 원본에도 적용된다

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[   1    2    3    4    5    6]
 [   7    8 9999 9999   11   12]
 [  13   14 9999 9999   17   18]
 [  19   20   21   22   23   24]]


## 10.3 Boolean Indexing

In [28]:
# 데모 배열 생성
a1 = np.arange(1, 25).reshape((4, 6)) #2차원 배열
pprint(a1)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [30]:
# 짝수인 요소 확인
even_arr = a1%2 == 0
pprint(even_arr)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:bool
Array's Data:
 [[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


In [31]:
a1[even_arr] # a1[a1%2 == 0] 같은 의미

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [32]:
np.sum(a1)

300

In [33]:
np.sum(a1[even_arr])

156