# 11. 배열 변환
Transpose, reshape, append, concatenate 등의 배열 변경 방법
## 11.1 전치(Transpose)
행과 열을 바꾸는 것

In [2]:
import numpy as np

def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

# Numpy 객체정보를 출력하는 용도

In [3]:
# 행렬 생성
a = np.random.randint(1, 10, (2, 3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 6 3]
 [6 2 7]]


In [4]:
pprint(a.T)

type:<class 'numpy.ndarray'>
shape: (3, 2), dimension: 2, dtype:int64
Array's Data:
 [[1 6]
 [6 2]
 [3 7]]


## 11.2 배열 형태 변경
ravel과 reshape 메서드 있다.
* revel : 배열을 1차원 배열로 만듬 (flatten?)
* reshape : 데이터 변경없이 지정된 shape로 변경
  
 ### **arr.ravel()**  
  ravel 메서드가 반환하는 배열의 요소를 수정하면 원본에서도 반영된다

In [6]:
a = np.random.randint(1,10, (2,3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[4 9 9]
 [5 6 2]]


In [7]:
a.ravel()

array([4, 9, 9, 5, 6, 2])

In [8]:
b = a.ravel()
pprint(b)

type:<class 'numpy.ndarray'>
shape: (6,), dimension: 1, dtype:int64
Array's Data:
 [4 9 9 5 6 2]


In [9]:
b[0] = 9999
pprint(b)

type:<class 'numpy.ndarray'>
shape: (6,), dimension: 1, dtype:int64
Array's Data:
 [9999    9    9    5    6    2]


In [11]:
pprint(a)  # b의 변경이 a에도 적용됨

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[9999    9    9]
 [   5    6    2]]


### **arr.reshape()**
arr의 shape를 변경한다. 실제 데이터를 변경하는 것이 아니고 shape 정보만 수정

In [12]:
a = np.random.randint(1,10, (2,3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 4 6]
 [1 9 4]]


In [13]:
result = a.reshape((3,2,1))
pprint(result)

type:<class 'numpy.ndarray'>
shape: (3, 2, 1), dimension: 3, dtype:int64
Array's Data:
 [[[1]
  [4]]

 [[6]
  [1]]

 [[9]
  [4]]]


## 11.3 배열 요소 추가 및 삭제
resize, append, insert, delete를 통해 배열의 요소를 바꿀 수 있다.  
  
  ### **resize()**
  * np.resize(a, new_shape) / arr.resize(new_shape, refcheck=True)
  
  reshape는 배열의 요소 수를 변경하지 않지만 resize는 배열의 요소 수를 줄이거나 늘린다.

In [3]:
a = np.random.randint(1,10, (2,6))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (2, 6), dimension: 2, dtype:int64
Array's Data:
 [[2 2 6 9 5 4]
 [1 2 3 8 9 4]]


In [4]:
# 요소 수 변경 없는 shape 변경
a.resize((6,2))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (6, 2), dimension: 2, dtype:int64
Array's Data:
 [[2 2]
 [6 9]
 [5 4]
 [1 2]
 [3 8]
 [9 4]]


In [5]:
# 요소 수가 늘어나는 변경
a.resize((2,10))
pprint(a) # 늘어난 요소는 0으로 채워짐

type:<class 'numpy.ndarray'>
shape: (2, 10), dimension: 2, dtype:int64
Array's Data:
 [[2 2 6 9 5 4 1 2 3 8]
 [9 4 0 0 0 0 0 0 0 0]]


In [6]:
# 요소 수가 줄어드는 변경
a = np.random.randint(1,10, (2,6))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (2, 6), dimension: 2, dtype:int64
Array's Data:
 [[6 8 7 8 7 7]
 [5 7 2 2 9 9]]


In [7]:
a.resize((3,3))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[6 8 7]
 [8 7 7]
 [5 7 2]]


### **append()**
* np.append(arr, values, axis=None)
* 배열의 끝에 값을 추가
* axis를 통해 추가되는 방향 지정

In [8]:
# 데모 배열 생성
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(10, 19).reshape(3, 3)
pprint(b)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


#### **case 1: axis를 지정하지 않는 경우**
axis를 지정하지 않으면 1차원 배열로 변경되어 결합

In [9]:
result = np.append(a,b)
pprint(result)

type:<class 'numpy.ndarray'>
shape: (18,), dimension: 1, dtype:int64
Array's Data:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


#### **case 2: axis=0**
* axis=0이면, shape[0]을 제외한 나머지 shape가 같아야한다

In [11]:
result = np.append(a,b, axis=0)
pprint(result)

type:<class 'numpy.ndarray'>
shape: (6, 3), dimension: 2, dtype:int64
Array's Data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


#### **case 3: axis=1**
* axis=1이면, shape[1]을 제외한 나머지 shape가 같아야한다

In [12]:
result = np.append(a,b, axis=1)
pprint(result)

type:<class 'numpy.ndarray'>
shape: (3, 6), dimension: 2, dtype:int64
Array's Data:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### **insert()**
* np.insert(arr, obj, values, axis=None)
* axis 지정하지 않으면 1차원 배열로
* 추가할 방향을 axis로 지정

In [13]:
a = np.arange(1,10).reshape(3,3)
pprint(a)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# a 배열을 1차원으로 변환하고 1번 인덱스에 999 추가
np.insert(a, 1, 999)

array([  1, 999,   2,   3,   4,   5,   6,   7,   8,   9])

In [15]:
# axis=0 --> 인덱스가 1인 row에 999 추가
np.insert(a,1,999, axis=0)

array([[  1,   2,   3],
       [999, 999, 999],
       [  4,   5,   6],
       [  7,   8,   9]])

In [16]:
# axis=1 --> 인덱스가 1인 column에 999 추가
np.insert(a,1,999, axis=1)

array([[  1, 999,   2,   3],
       [  4, 999,   5,   6],
       [  7, 999,   8,   9]])

### **delete()**
* np.delete(arr, obj, axis=None)
* axis지정 안하면 1차원 배열로
* 삭제할 방향 axis로 지정
* 원본을 변경하지 않으며 새로운 배열을 반환

In [17]:
a = np.arange(1,10).reshape(3,3)
pprint(a)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# 1차원으로 변환 후 1번 인덱스 삭제
np.delete(a,1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# index 1인 row 삭제
np.delete(a,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [20]:
# index 1인 column 삭제
np.delete(a,1,axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

## 11.4 배열 결합
### **np.concatenate**
* concatenate((a1,a2,...),axis=0)

In [21]:
# 데모 배열
a = np.arange(1, 7).reshape((2, 3))
pprint(a)
b = np.arange(7, 13).reshape((2, 3))
pprint(b)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 2 3]
 [4 5 6]]
type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[ 7  8  9]
 [10 11 12]]


In [22]:
result = np.concatenate((a,b)) # axis default 0
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
result = np.concatenate((a,b), axis=1)
result

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### **수직방향 배열 결합: np.vstack**
* np.vstack(tup)
    * tup = 튜플
* 튜플로 설정된 여러 배열을 수직방향으로 연결 (axis=0)
* np.concatenate(tup, axis=0)과 동일

In [24]:
# 데모 배열
a = np.arange(1, 7).reshape((2, 3))
pprint(a)
b = np.arange(7, 13).reshape((2, 3))
pprint(b)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[1 2 3]
 [4 5 6]]
type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int64
Array's Data:
 [[ 7  8  9]
 [10 11 12]]


In [25]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.vstack((a,b,a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### **수평방향 배열 결합: np.hstack**
* np.hstack(tup)
    * tup = 튜플
* 튜플로 설정된 여러 배열을 수평방향으로 연결 (axis=1)
* np.concatenate(tup, axis=1)과 동일

In [28]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [29]:
np.hstack((a,b,a,b))

array([[ 1,  2,  3,  7,  8,  9,  1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12,  4,  5,  6, 10, 11, 12]])

## 11.5 배열 분리
* np.hsplit(): 지정한 배열을 수평(column) 방향으로 분할
* np.vsplit(): 지정한 배열을 수직(row) 방향으로 분할
  
  **배열 수평 분할**
  * np.hsplit(arr, indices_or_sections)
  * 배열을 수평방향으로 분할 (column)

In [30]:
a = np.arange(1, 25).reshape((4, 6))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [31]:
result = np.hsplit(a, 2)
result

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]), array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

![hsplit](https://taewanmerepo.github.io/2018/01/numpy/sp01.png)

In [32]:
result = np.hsplit(a,3) # 세 그룹으로 분할
result

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]), array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]), array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [34]:
result = np.hsplit(a, [1,3,5]) # 여러 구간으로 분할
result # 1 다음 구분, 3다음 구분, 5다음 구분

[array([[ 1],
        [ 7],
        [13],
        [19]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]), array([[ 6],
        [12],
        [18],
        [24]])]

![0](https://taewanmerepo.github.io/2018/01/numpy/sp03.png)

**배열 수직 분할**  
* np.vsplit(arr, indices_or_sections)
* 배열을 수직방향으로 분할 (row)

In [35]:
# 분할 대상 배열 생성
a = np.arange(1, 25).reshape((4, 6))
pprint(a)

type:<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:int64
Array's Data:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [41]:
result = np.vsplit(a,2) # 2개 그룹으로 분할
result

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

![11](https://taewanmerepo.github.io/2018/01/numpy/sp04.png)

In [42]:
result = np.vsplit(a,4) # 4개 그룹으로 분할
result

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]

In [44]:
result = np.vsplit(a, [1,3]) # 여려 구간으로 분할
result # 1다음 분할, 3다음 분할 / 1, 2-3, 4 로 분할

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]

![111](https://taewanmerepo.github.io/2018/01/numpy/sp06.png)